### ISSUE TITLE
Scripts for Translate-Test

### ISSUE THREAD

**Issue by adymaharana** [facebookresearch/MLQA#2]
Hi, 

Thanks for the valuable dataset! It is so much easier to add a multilingual component to QA projects now. :) Will you also be releasing the scripts for different evaluation methodologies? I am interested in the Translate-Test method and I see that you have referenced [this](https://arxiv.org/pdf/1809.03275.pdf) paper for it. Did you use their method of pretraining an NMT model too? Kindly let me know. Thanks!

**Comment by patrick-s-h-lewis** [comment]
Dear Adymaharana,

Thanks for your interest in the project :)
 
>>> Will you also be releasing the scripts for different evaluation methodologies?

We hope to release as much of our implementations as possible.

>>> Did you use their method of pretraining an NMT model too? 

As mentioned in the paper, we use Facebook's Production Machine Translation system.

Patrick
