### ISSUE TITLE
OS translate-train translate-test datasets?

### ISSUE THREAD

**Issue by Timoeller** [facebookresearch/MLQA#3]
Hey Patrick,
awesome work you are doing there on getting cool ML also to other languages.
Is there a way you guys open source the automatically translated datasets for translate-train and/or translate-test as well?

**Comment by patrick-s-h-lewis** [comment]
Hi Timo,

I'm looking into this,  

Patrick

**Comment by josecannete** [comment]
Hi Patrick @patrick-s-h-lewis, any news about this?

Thank you so much!

**Comment by patrick-s-h-lewis** [comment]
I think we're very close to getting machine-translations open-sourced, hopefully next week.

**Comment by patrick-s-h-lewis** [comment]
Translate-train and Translate-test now available:

https://github.com/facebookresearch/MLQA#translate-train-and-translate-test-data

**Comment by F95GIT** [comment]
Hey, i tried to use the translated german version "de_squad-translate-train-train-v1.1.json" but when I am trying to load it it always raises an Error in the read_squad_examples script:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-39-1707ce97e6b5> in <module>
      2 examples2 = read_squad_examples(input_file=input_file2,
      3                                 is_training=True,
----> 4                                 version_2_with_negative=True
      5                                 )

~/Downloads/huggingface-transformers-971c9b0/examples/utils_squad.py in read_squad_examples(input_file, is_training, version_2_with_negative)
    145                 start_position = None
    146                 end_position = None
--> 147                 orig_answer_text = None
    148                 is_impossible = False
    149                 if is_training:

KeyError: 'is_impossible'`


Do you maybe have a solution for my problem ?

Thank you
